In [1]:
import pandas as pd

frutas = [
    {"nombre": "manzana", "precio": 200},
    {"nombre": "banana", "precio": 150},
]
df = pd.DataFrame(frutas)
print(df)

    nombre  precio
0  manzana     200
1   banana     150

In [2]:
alumnos = [
    {"nombre": "Ana", "nota1": 8, "nota2": 7},
    {"nombre": "Luis", "nota1": 5, "nota2": 6},
    {"nombre": "Carla", "nota1": 9, "nota2": 10},
    {"nombre": "Pedro", "nota1": 4, "nota2": 5},
]

def procesar_alumnos(lista):
    promedio = 0 
    promedio_general= 0
    Alumnos_aprobados = []
    for alumno in lista:
        promedio = ((alumno["nota1"] + alumno["nota2"] )/2)
        alumno["promedio"] = promedio
        if promedio >= 6 :
            Alumnos_aprobados.append(alumno["nombre"])
        promedio_general +=  promedio / len(lista)
   



    return lista, Alumnos_aprobados, promedio_general



procesar_alumnos(alumnos)

([{'nombre': 'Ana', 'nota1': 8, 'nota2': 7, 'promedio': 7.5},
  {'nombre': 'Luis', 'nota1': 5, 'nota2': 6, 'promedio': 5.5},
  {'nombre': 'Carla', 'nota1': 9, 'nota2': 10, 'promedio': 9.5},
  {'nombre': 'Pedro', 'nota1': 4, 'nota2': 5, 'promedio': 4.5}],
 ['Ana', 'Carla'],
 6.75)

In [3]:
df = pd.DataFrame(alumnos)
print(df)
print(df.columns)
print(df.describe())
print(df.head(2))

  nombre  nota1  nota2  promedio
0    Ana      8      7       7.5
1   Luis      5      6       5.5
2  Carla      9     10       9.5
3  Pedro      4      5       4.5
Index(['nombre', 'nota1', 'nota2', 'promedio'], dtype='object')
          nota1      nota2  promedio
count  4.000000   4.000000  4.000000
mean   6.500000   7.000000  6.750000
std    2.380476   2.160247  2.217356
min    4.000000   5.000000  4.500000
25%    4.750000   5.750000  5.250000
50%    6.500000   6.500000  6.500000
75%    8.250000   7.750000  8.000000
max    9.000000  10.000000  9.500000
  nombre  nota1  nota2  promedio
0    Ana      8      7       7.5
1   Luis      5      6       5.5

In [4]:
df_aprobados = df[df["promedio"]>= 6 ]
print(df_aprobados)

  nombre  nota1  nota2  promedio
0    Ana      8      7       7.5
2  Carla      9     10       9.5

In [5]:
df_ventas = pd.read_csv("ventas.csv")

In [6]:
df_ventas

   producto  precio  cantidad
0      Taza    1500        20
1  Cuaderno     800        45
2  Lapicera     300       100
3   Mochila    5200         8

In [7]:
df_ventas["precio"]

0    1500
1     800
2     300
3    5200
Name: precio, dtype: int64

In [8]:
df_ventas[["precio" , "producto"]]

   precio  producto
0    1500      Taza
1     800  Cuaderno
2     300  Lapicera
3    5200   Mochila

In [9]:
df_ventas["categoria"] = ["Hogar" ,"papeleria" , "papeleria" , "Hogar"]

In [10]:
print(df_ventas)

   producto  precio  cantidad  categoria
0      Taza    1500        20      Hogar
1  Cuaderno     800        45  papeleria
2  Lapicera     300       100  papeleria
3   Mochila    5200         8      Hogar