In [2]:
import pandas as pd

frutas = [
    {"nombre": "manzana", "precio": 200},
    {"nombre": "banana", "precio": 150},
]
df = pd.DataFrame(frutas)
print(df)

    nombre  precio
0  manzana     200
1   banana     150

In [3]:
alumnos = [
    {"nombre": "Ana", "nota1": 8, "nota2": 7},
    {"nombre": "Luis", "nota1": 5, "nota2": 6},
    {"nombre": "Carla", "nota1": 9, "nota2": 10},
    {"nombre": "Pedro", "nota1": 4, "nota2": 5},
]

def procesar_alumnos(lista):
    promedio = 0 
    promedio_general= 0
    Alumnos_aprobados = []
    for alumno in lista:
        promedio = ((alumno["nota1"] + alumno["nota2"] )/2)
        alumno["promedio"] = promedio
        if promedio >= 6 :
            Alumnos_aprobados.append(alumno["nombre"])
        promedio_general +=  promedio / len(lista)
   



    return lista, Alumnos_aprobados, promedio_general



procesar_alumnos(alumnos)

([{'nombre': 'Ana', 'nota1': 8, 'nota2': 7, 'promedio': 7.5},
  {'nombre': 'Luis', 'nota1': 5, 'nota2': 6, 'promedio': 5.5},
  {'nombre': 'Carla', 'nota1': 9, 'nota2': 10, 'promedio': 9.5},
  {'nombre': 'Pedro', 'nota1': 4, 'nota2': 5, 'promedio': 4.5}],
 ['Ana', 'Carla'],
 6.75)

In [4]:
df = pd.DataFrame(alumnos)
print(df)
print(df.columns)
print(df.describe())
print(df.head(2))

  nombre  nota1  nota2  promedio
0    Ana      8      7       7.5
1   Luis      5      6       5.5
2  Carla      9     10       9.5
3  Pedro      4      5       4.5
Index(['nombre', 'nota1', 'nota2', 'promedio'], dtype='object')
          nota1      nota2  promedio
count  4.000000   4.000000  4.000000
mean   6.500000   7.000000  6.750000
std    2.380476   2.160247  2.217356
min    4.000000   5.000000  4.500000
25%    4.750000   5.750000  5.250000
50%    6.500000   6.500000  6.500000
75%    8.250000   7.750000  8.000000
max    9.000000  10.000000  9.500000
  nombre  nota1  nota2  promedio
0    Ana      8      7       7.5
1   Luis      5      6       5.5

In [5]:
df_aprobados = df[df["promedio"]>= 6 ]
print(df_aprobados)

  nombre  nota1  nota2  promedio
0    Ana      8      7       7.5
2  Carla      9     10       9.5

In [6]:
df_ventas = pd.read_csv("ventas.csv")

In [7]:
df_ventas

   producto  precio  cantidad
0      Taza    1500        20
1  Cuaderno     800        45
2  Lapicera     300       100
3   Mochila    5200         8

In [8]:
df_ventas["precio"]

0    1500
1     800
2     300
3    5200
Name: precio, dtype: int64

In [9]:
df_ventas[["precio" , "producto"]]

   precio  producto
0    1500      Taza
1     800  Cuaderno
2     300  Lapicera
3    5200   Mochila

In [10]:
df_ventas["categoria"] = ["Hogar" ,"papeleria" , "papeleria" , "Hogar"]

In [11]:
print(df_ventas)

   producto  precio  cantidad  categoria
0      Taza    1500        20      Hogar
1  Cuaderno     800        45  papeleria
2  Lapicera     300       100  papeleria
3   Mochila    5200         8      Hogar

In [12]:
print(df_ventas.groupby("categoria")["precio"].mean())
print(df_ventas.groupby("categoria")["cantidad"].sum())

categoria
Hogar        3350.0
papeleria     550.0
Name: precio, dtype: float64
categoria
Hogar         28
papeleria    145
Name: cantidad, dtype: int64

In [13]:
df_ordenado = df_ventas.sort_values("precio",ascending = True)
print(df_ordenado)
df_desc = df_ventas.sort_values("precio", ascending = False)
print(df_desc)

   producto  precio  cantidad  categoria
2  Lapicera     300       100  papeleria
1  Cuaderno     800        45  papeleria
0      Taza    1500        20      Hogar
3   Mochila    5200         8      Hogar
   producto  precio  cantidad  categoria
3   Mochila    5200         8      Hogar
0      Taza    1500        20      Hogar
1  Cuaderno     800        45  papeleria
2  Lapicera     300       100  papeleria

In [14]:
fila_nueva = pd.DataFrame([{"producto" : "Mate", "precio" : 75000 , "cantidad" : 25 , "categoria" : "Hogar"}])
df_actualizado = pd.concat([df_ventas , fila_nueva ], ignore_index = True) 
print(df_actualizado)

   producto  precio  cantidad  categoria
0      Taza    1500        20      Hogar
1  Cuaderno     800        45  papeleria
2  Lapicera     300       100  papeleria
3   Mochila    5200         8      Hogar
4      Mate   75000        25      Hogar

In [15]:
df_actualizado.loc[df_actualizado["producto" ] == "Mate" , "precio"] = 7500
print(df_actualizado)

   producto  precio  cantidad  categoria
0      Taza    1500        20      Hogar
1  Cuaderno     800        45  papeleria
2  Lapicera     300       100  papeleria
3   Mochila    5200         8      Hogar
4      Mate    7500        25      Hogar

In [16]:
with open("ventas_grandes.csv", "w") as archivo:
    archivo.write("""producto,precio,cantidad,categoria
Taza,1500,20,Hogar
Cuaderno,800,45,papeleria
Lapicera,300,100,Papeleria
Mochila,5200,8,hogar
Termo,2100,,Hogar
Cartuchera,950,30,papeleria
Termo,2100,,Hogar
Pava,-800,12,Hogar
Resaltador,450,,Papeleria
Bolso,3800,6,HOGAR""")

In [17]:
df_ventas_grandes = pd.read_csv("ventas_grandes.csv")
print(df_ventas_grandes.info())
print(df_ventas_grandes.isnull().sum())
print(df_ventas_grandes.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   producto   10 non-null     object
 1   precio     10 non-null     int64
 2   cantidad   7 non-null      float64
 3   categoria  10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None
producto     0
precio       0
cantidad     3
categoria    0
dtype: int64
1

In [18]:
df_ventas_grandes["categoria"].unique()

array(['Hogar', 'papeleria', 'Papeleria', 'hogar', 'HOGAR'], dtype=object)

In [19]:
df_ventas_grandes["categoria"] = df_ventas_grandes["categoria"].str.lower()

In [20]:
df_ventas_grandes_S_duplicates = df_ventas_grandes.drop_duplicates()
df_ventas_grandes_S_duplicates

     producto  precio  cantidad  categoria
0        Taza    1500      20.0      hogar
1    Cuaderno     800      45.0  papeleria
2    Lapicera     300     100.0  papeleria
3     Mochila    5200       8.0      hogar
4       Termo    2100       NaN      hogar
5  Cartuchera     950      30.0  papeleria
7        Pava    -800      12.0      hogar
8  Resaltador     450       NaN  papeleria
9       Bolso    3800       6.0      hogar

In [21]:
df_ventas_grandes_S_duplicates.loc[df_ventas_grandes_S_duplicates["producto"] == "Pava" , "precio"] = 800
df_ventas_grandes_S_duplicates["cantidad"] = df_ventas_grandes_S_duplicates["cantidad"].fillna(df_ventas_grandes_S_duplicates.groupby("categoria")["cantidad"].transform("median"))

C:\Users\santi\AppData\Local\Temp\ipykernel_3804\1641990490.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ventas_grandes_S_duplicates["cantidad"] = df_ventas_grandes_S_duplicates["cantidad"].fillna(df_ventas_grandes_S_duplicates.groupby("categoria")["cantidad"].transform("median"))

In [22]:
print(df_ventas_grandes_S_duplicates)
df_ventas_grandes_S_duplicates.info()
df_ventas_grandes_S_duplicates.isnull().sum()

     producto  precio  cantidad  categoria
0        Taza    1500      20.0      hogar
1    Cuaderno     800      45.0  papeleria
2    Lapicera     300     100.0  papeleria
3     Mochila    5200       8.0      hogar
4       Termo    2100      10.0      hogar
5  Cartuchera     950      30.0  papeleria
7        Pava     800      12.0      hogar
8  Resaltador     450      45.0  papeleria
9       Bolso    3800       6.0      hogar
<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   producto   9 non-null      object
 1   precio     9 non-null      int64
 2   cantidad   9 non-null      float64
 3   categoria  9 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 360.0+ bytes

producto     0
precio       0
cantidad     0
categoria    0
dtype: int64